package com.cyberark.model;

import lombok.Data;

import javax.persistence.*;
import java.util.Date;

@Data
@Entity
@Table(name="bh_placement")
public class BH_Placement {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long placementID;
    @Column(name = "jobPostingID")
    private long jobPostingID;
    @Column(name = "userID")
    private long userID;
    @Column(name = "dateBegin")
    private Date dateBegin;
    @Column(name = "dateEnd")
    private Date dateEnd;
    @Column(name = "employmentType")
    private String employmentType;
    @Column(name = "salary")
    private String salary;
    @Column(name = "salaryUnit")
    private long salaryUnit;
    @Column(name = "reportedMargin")
    private Double reportedMargin;
    @Column(name = "referralFee")
    private long referralFee;
    @Column(name = "referralFeeType")
    private String referralFeeType;
    @Column(name = "hoursPerDay")
    private long hoursPerDay;
    @Column(name = "status")
    private String status;
    @Column(name = "dateAdded")
    private Date dateAdded;
    @Column(name = "dateEffective")
    private Date dateEffective;
    @Column(name = "dateClientEffective")
    private Date dateClientEffective;
    @Column(name = "clientBillRate")
    private Double clientBillRate;
    @Column(name = "daysGuaranteed")
    private long daysGuaranteed;
    @Column(name = "daysProRated")
    private long daysProRated;
    @Column(name = "employeeType")
    private String employeeType;
    @Column(name = "overtimeRate")
    private Double overtimeRate;
    @Column(name = "clientOvertimeRate")
    private Double clientOvertimeRate;
    @Column(name = "reportTo")
    private String reportTo;
    @Column(name = "costCenter")
    private String costCenter;
    @Column(name = "optionsPackage")
    private String optionsPackage;
    @Column(name = "bonusPackage")
    private String bonusPackage;
    @Column(name = "hoursOfOperation")
    private String hoursOfOperation;
    @Column(name = "durationWeeks")
    private Double durationWeeks;
    @Column(name = "payRate")
    private long payRate;
    @Column(name = "fee")
    private long fee;
    @Column(name = "comments")
    private String comments;
    @Column(name = "otherHourlyFee")
    private Double otherHourlyFee;
    @Column(name = "otherHourlyFeeComments")
    private String otherHourlyFeeComments;
    @Column(name = "salesManagerPercentGrossMargin")
    private Double salesManagerPercentGrossMargin;
    @Column(name = "recruitingManagerPercentGrossMargin")
    private Double recruitingManagerPercentGrossMargin;
    @Column(name = "invoiceID")
    private long invoiceID;
    @Column(name = "taxRate")
    private Double taxRate;
    @Column(name = "taxState")
    private String taxState;
    @Column(name = "invoiceGroup")
    private String invoiceGroup;
    @Column(name = "projectCodeList")
    private String projectCodeList;
    @Column(name = "invoiceGroupID")
    private long invoiceGroupID;
    @Column(name = "approvingUserID")
    private long approvingUserID;
    @Column(name = "backupApprovingUserID")
    private long backupApprovingUserID;
    @Column(name = "shiftID")
    private long shiftID;
    @Column(name = "terminationReason")
    private String terminationReason;
    @Column(name = "otExemption")
    private long otExemption;
    @Column(name = "housingManagerID")
    private long housingManagerID;
    @Column(name = "housingStatus")
    private String housingStatus;
    @Column(name = "vendorClientCorporationID")
    private long vendorClientCorporationID;
    @Column(name = "canEnterTime")
    private Boolean canEnterTime;
    @Column(name = "quitJob")
    private Boolean quitJob;
    @Column(name = "trackNumber")
    private long trackNumber;
    @Column(name = "branchID")
    private long branchID;
    @Column(name = "lastApprovedPlacementChangeRequestID")
    private long lastApprovedPlacementChangeRequestID;
    @Column(name = "isMultirate")
    private Boolean isMultirate;
    @Column(name = "locationID")
    private long locationID;
    @Column(name = "jobCodeID")
    private long jobCodeID;
    @Column(name = "lineID")
    private long lineID;
    @Column(name = "billingProfileID")
    private long billingProfileID;
    @Column(name = "placementTimeAndExpenseID")
    private long placementTimeAndExpenseID;
    @Column(name = "placementTaxExemptionStatusLookupID")
    private long placementTaxExemptionStatusLookupID;
    @Column(name = "generalLedgerServiceCodeID")
    private long generalLedgerServiceCodeID;
    @Column(name = "employmentStartDate")
    private long employmentStartDate;
    @Column(name = "positionCode")
    private String positionCode;
    @Column(name = "benefitGroup")
    private String benefitGroup;
    @Column(name = "payGroupLookupID")
    private long payGroupLookupID;
    @Column(name = "payrollEmployeeTypeLookupID")
    private long payrollEmployeeTypeLookupID;
    @Column(name = "payrollSyncStatusLookupID")
    private long payrollSyncStatusLookupID;
    @Column(name = "externalID")
    private String externalID;
    @Column(name = "onboardingStatus")
    private String onboardingStatus;
    @Column(name = "onboardingPercentComplete")
    private long onboardingPercentComplete;
    @Column(name = "onboardingDocumentSentCount")
    private long onboardingDocumentSentCount;
    @Column(name = "onboardingDocumentReceivedCount")
    private long onboardingDocumentReceivedCount;
    @Column(name = "legalBusinessEntityID")
    private long legalBusinessEntityID;
    @Column(name = "payGroup")
    private String payGroup;
    @Column(name = "estaffGUID")
    private long estaffGUID;
    @Column(name = "isWorkFromHome")
    private Boolean isWorkFromHome;
    @Column(name = "timesheetCycleID")
    private long timesheetCycleID;
    @Column(name = "clientRating")
    private String clientRating;
    @Column(name = "bteSyncStatusLookupID")
    private long bteSyncStatusLookupID;
    @Column(name = "lastBteSyncDate")
    private Date lastBteSyncDate;
    @Column(name = "estimatedEndDate")
    private Date estimatedEndDate;

    public BH_Placement() {
    }
}
