package com.cyberark.model;

import lombok.Data;

import javax.persistence.*;
import java.util.Date;

@Data
@Entity
@Table(name="bh_usercontact")
public class BH_UserContact {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long userID;
    @Column(name = "countryID")
    private long countryID;
    @Column(name = "name")
    private String name;
    @Column(name = "address1")
    private String address1;
    @Column(name = "address2")
    private String address2;
    @Column(name = "city")
    private String city;
    @Column(name = "state")
    private long state;
    @Column(name = "zip")
    private String zip;
    @Column(name = "email_old")
    private String email_old;
    @Column(name = "dateAdded")
    private Date dateAdded;
    @Column(name = "description")
    private String description;
    @Column(name = "corporationID")
    private long corporationID;
    @Column(name = "phone")
    private String phone;
    @Column(name = "experience")
    private long experience;
    @Column(name = "hourlyRate")
    private long hourlyRate;
    @Column(name = "dayRate")
    private long dayRate;
    @Column(name = "salary")
    private long salary;
    @Column(name = "occupation")
    private String occupation;
    @Column(name = "referredBy")
    private String referredBy;
    @Column(name = "isPublic")
    private Boolean isPublic;
    @Column(name = "skillset")
    private String skillset;
    @Column(name = "companyName")
    private String companyName;
    @Column(name = "companyURL")
    private String companyURL;
    @Column(name = "companyDescription")
    private String companyDescription;
    @Column(name = "isValidEmail")
    private Boolean isValidEmail;
    @Column(name = "recentClientList")
    private String recentClientList;
    @Column(name = "recentAwardList")
    private String recentAwardList;
    @Column(name = "categoryID")
    private long categoryID;
    @Column(name = "registrationType")
    private String registrationType;
    @Column(name = "numEmployees")
    private long numEmployees;
    @Column(name = "dateOfBirth")
    private Date dateOfBirth;
    @Column(name = "fax")
    private String fax;
    @Column(name = "pager")
    private String pager;
    @Column(name = "mobile")
    private String mobile;
    @Column(name = "taxID")
    private String taxID;
    @Column(name = "ssn")
    private String ssn;
    @Column(name = "internationalMailingAddress")
    private String internationalMailingAddress;
    @Column(name = "checkPayableTo")
    private String checkPayableTo;
    @Column(name = "dateAvailable")
    private Date dateAvailable;
    @Column(name = "source")
    private String source;
    @Column(name = "employmentPreference")
    private String employmentPreference;
    @Column(name = "certifications")
    private String certifications;
    @Column(name = "educationDegree")
    private String educationDegree;
    @Column(name = "workAuthorized")
    private String workAuthorized;
    @Column(name = "travelLimit")
    private long travelLimit;
    @Column(name = "bhTimestamp")
    private Date bhTimestamp;
    @Column(name = "willTravel")
    private long willTravel;
    @Column(name = "desiredLocations")
    private String desiredLocations;
    @Column(name = "willRelocate")
    private long willRelocate;
    @Column(name = "firstName")
    private String firstName;
    @Column(name = "lastName")
    private String lastName;
    @Column(name = "degreeList")
    private String degreeList;
    @Column(name = "dateLastComment")
    private Date dateLastComment;
    @Column(name = "externalEmail")
    private String externalEmail;
    @Column(name = "namePrefix")
    private String namePrefix;
    @Column(name = "nameSuffix")
    private String nameSuffix;
    @Column(name = "middleName")
    private String middleName;
    @Column(name = "dateAvailableEnd")
    private Date dateAvailableEnd;
    @Column(name = "email")
    private String email;
    @Column(name = "nickname")
    private String nickname;
    @Column(name = "salaryLow")
    private long salaryLow;
    @Column(name = "dayRateLow")
    private long dayRateLow;
    @Column(name = "hourlyRateLow")
    private long hourlyRateLow;
    @Column(name = "lastNote_denormalized")
    private String lastNote_denormalized;
    @Column(name = "secondaryCountryID")
    private long secondaryCountryID;
    @Column(name = "secondaryAddress1")
    private String secondaryAddress1;
    @Column(name = "secondaryAddress2")
    private String secondaryAddress2;
    @Column(name = "secondaryCity")
    private String secondaryCity;
    @Column(name = "secondaryState")
    private String secondaryState;
    @Column(name = "workPhone")
    private String workPhone;
    @Column(name = "phone2")
    private String phone2;
    @Column(name = "phone3")
    private String phone3;
    @Column(name = "fax2")
    private String fax2;
    @Column(name = "fax3")
    private String fax3;
    @Column(name = "email2")
    private String payGroup;
    @Column(name = "email3")
    private String email3;
    @Column(name = "gender")
    private String gender;
    @Column(name = "veteran")
    private String veteran;
    @Column(name = "disability")
    private String disability;
    @Column(name = "ethnicity")
    private String ethnicity;
    @Column(name = "referredByUserID")
    private long referredByUserID;
    @Column(name = "ownerCorporationID")
    private long ownerCorporationID;
    @Column(name = "recordTypeBits")
    private long recordTypeBits;
    @Column(name = "clientCorporationID")
    private long clientCorporationID;
    @Column(name = "status")
    private String status;
    @Column(name = "isDeleted")
    private String isDeleted;
    @Column(name = "ownerUserIDList")
    private String ownerUserIDList;
    @Column(name = "skillIDList")
    private String skillIDList;
    @Column(name = "categoryIDList")
    private String categoryIDList;
    @Column(name = "specialtyIDList")
    private String specialtyIDList;
    @Column(name = "businessSectorIDList")
    private String businessSectorIDList;
    @Column(name = "massMailOptOut")
    private long massMailOptOut;
    @Column(name = "federalFilingStatus")
    private String federalFilingStatus;
    @Column(name = "federalExemptions")
    private long federalExemptions;
    @Column(name = "federalAddtionalWitholdingsAmount")
    private long federalAddtionalWitholdingsAmount;
    @Column(name = "taxState")
    private long taxState;
    @Column(name = "stateExemptions")
    private long stateExemptions;
    @Column(name = "stateAddtionalWitholdingsAmount")
    private long stateAddtionalWitholdingsAmount;
    @Column(name = "migrateGUID")
    private long migrateGUID;
    @Column(name = "localFilingStatus")
    private String localFilingStatus;
    @Column(name = "localTaxCode")
    private String localTaxCode;
    @Column(name = "localExemptions")
    private long localExemptions;
    @Column(name = "localAddtionalWitholdingsAmount")
    private long localAddtionalWitholdingsAmount;
    @Column(name = "I9OnFile")
    private long I9OnFile;
    @Column(name = "dateI9Expiration")
    private Date dateI9Expiration;
    @Column(name = "paperWorkOnFile")
    private String paperWorkOnFile;
    @Column(name = "reportToUserID")
    private long reportToUserID;
    @Column(name = "smsOptIn")
    private Boolean smsOptIn;
    @Column(name = "branchID")
    private long branchID;
    @Column(name = "isAnonymized")
    private Boolean isAnonymized;
    @Column(name = "isExempt")
    private Boolean isExempt;
    @Column(name = "twoJobs")
    private Boolean twoJobs;
    @Column(name = "totalDependentClaimAmount")
    private long totalDependentClaimAmount;
    @Column(name = "otherIncomeAmount")
    private long otherIncomeAmount;
    @Column(name = "otherDeductionsAmount")
    private long otherDeductionsAmount;
    @Column(name = "federalExtraWithholdingAmount")
    private long federalExtraWithholdingAmount;
    @Column(name = "addressSourceID")
    private long addressSourceID;
    @Column(name = "dateLastModified")
    private Date dateLastModified;

    public BH_UserContact() {
    }
}
